on:
  workflow_call:

jobs:
  build:
    name: "Build Projects"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
        shell: bash
      - run: yarn build-storybook --webpack-stats-json
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: bundles_${{ github.sha }}
          path: storybook-static
          retention-days: 1
