on:
  workflow_call:
    secrets:
      CHROMATIC_PROJECT_TOKEN:
        required: true

jobs:
  lint:
    name: "Lint Sources"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
        shell: bash
      - run: yarn flow-typed-install
        shell: bash
      - run: yarn flow
        shell: bash
      - run: yarn lint
        shell: bash
  test:
    name: "Test Project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn test --coverage
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ github.sha }}
          path: |
            ./coverage
          if-no-files-found: error
          retention-days: 1
  coverage:
    name: "Report Coverage"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: coverage_${{ github.sha }}
      - uses: codecov/codecov-action@v4
  chromatic:
    name: "Run Visual Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: bundles_${{ github.sha }}
          path: storybook-static
      - uses: chromaui/action@v10
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          onlyChanged: true

